
CREATE DATABASE BTL_HIGHWAYTOHELL

USE BTL_HIGHWAYTOHELL

DROP DATABASE BTL_HIGHWAYTOHELL

CREATE TABLE JOB (
	JobID INT, 
	JobName NVARCHAR(100),
	JobStartTime DATE,
	JobEndTime DATE,
	JobDescription NVARCHAR(MAX),
	JobImage NVARCHAR(MAX),
	JobStatus NVARCHAR (20),
	CONSTRAINT PRK_JOB_JobID PRIMARY KEY(JobID),

	TypeJobID INT,
	HumanResourceID INT,
);



CREATE TABLE TYPEJOB (
	TypeJobID INT,
	TypeJobName NVARCHAR(100),
	CONSTRAINT PRK_TYPEJOB_TypeJobID PRIMARY KEY(TypeJobID),
	CONSTRAINT UNQ_TYPEJOB_TypeJobName UNIQUE (TypeJobName)
);

CREATE TABLE COMPANY (
	CompanyID INT,
	CompanyName NVARCHAR(50),
	CompanyDescription NVARCHAR(MAX),
	CompanyWebsite NVARCHAR(MAX),
	CONSTRAINT PRK_COMPANY_CompanyID PRIMARY KEY(CompanyID),
	CONSTRAINT UNQ_COMPANY_CompanyName UNIQUE(CompanyName),
); 


CREATE TABLE USERS (
	UserID INT,
	UserName NVARCHAR(400),
	UserPassword NVARCHAR (MAX),
	UserProfile NVARCHAR(MAX),
	UserRole NVARCHAR(20),
	CONSTRAINT PRK_USERS_UserID PRIMARY KEY(UserID),
	CONSTRAINT UNQ_USERS_UserName UNIQUE(UserName),
);


CREATE TABLE HR (
	HumanResourceID INT,
	HumanResourceName NVARCHAR (300),
	HumanResourcePassword NVARCHAR(MAX),
	HumanResourceProfile NVARCHAR(MAX),
	HumanResourceStatus NVARCHAR(10),
	HumanResourceRole NVARCHAR(10),
	CONSTRAINT PRK_HR_HumanResourceID PRIMARY KEY(HumanResourceID),
	CONSTRAINT UNQ_HR_HumanResourceName UNIQUE(HumanResourceName),

	CompanyID INT,

);


CREATE TABLE AD (
	AdminID INT,
	AdminName NVARCHAR(50),
	AdminPassword NVARCHAR(50),
	AdminRole NVARCHAR (50),
	CONSTRAINT PRK_AD_AdminID PRIMARY KEY(AdminID),

	JobID INT,
	HumanResourceID INT

);

CREATE TABLE FORM (
	FormID INT,
	UserID INT,
	HumanResourceID INT,
	FormCV NVARCHAR (MAX)
	CONSTRAINT PRK_FORM_FormID PRIMARY KEY(FormID),
);



ALTER TABLE JOB ADD CONSTRAINT FRK_JOB_TYPEJOB_TypeJobID FOREIGN KEY (TypeJobID)  REFERENCES TYPEJOB(TypeJobID)

ALTER TABLE JOB ADD CONSTRAINT FRK_JOB_HR_HumanResourceID FOREIGN KEY (HumanResourceID)  REFERENCES HR(HumanResourceID)

ALTER TABLE HR ADD CONSTRAINT FRK_HR_COMPANY_CompanyID FOREIGN KEY (CompanyID)  REFERENCES COMPANY(CompanyID)

ALTER TABLE FORM ADD CONSTRAINT FRK_FORM_USERS_UserID FOREIGN KEY (UserID)  REFERENCES USERS(UserID)

ALTER TABLE FORM ADD CONSTRAINT FRK_FORM_HR_HumanResourceID FOREIGN KEY (HumanResourceID)  REFERENCES HR(HumanResourceID)

ALTER TABLE AD ADD CONSTRAINT FRK_AD_JOB_JobID FOREIGN KEY (JobID)  REFERENCES JOB(JobID)

ALTER TABLE AD ADD CONSTRAINT FRK_AD_HR_HumanResourceID FOREIGN KEY (HumanResourceID)  REFERENCES HR(HumanResourceID)
