//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Job.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongTy
    {
        public int MaCongTy { get; set; }
        public string TenCongTy { get; set; }
        public string HinhAnh { get; set; }
        public string DiaDiem { get; set; }
        public Nullable<int> MaCongViec { get; set; }
    
        public virtual CongViec CongViec { get; set; }
    }
}
